/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import models.InsuranceCoverage;

/**
 *
 * @author rakadadevarushikamidi
 */
public class CreateInsuranceCoverageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateInsuranceCoverageJPanel
     */
    InsuranceCoverage insuranceCoverage;
    public CreateInsuranceCoverageJPanel(InsuranceCoverage insuranceCoverage) {
        initComponents();
        this.insuranceCoverage = insuranceCoverage; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeductable = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtPremium = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtCorporateID = new javax.swing.JTextField();
        lblCorporateID = new javax.swing.JLabel();
        txtDeductable = new javax.swing.JTextField();
        txtBenefits = new javax.swing.JTextField();

        lblDeductable.setText("Deductable:");

        lblPremium.setText("Premium:");

        lblBenefits.setText("Benefits:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Insurance Coverage");

        txtCorporateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorporateIDActionPerformed(evt);
            }
        });

        lblCorporateID.setText("Corporate ID:");

        txtDeductable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeductableActionPerformed(evt);
            }
        });

        txtBenefits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenefitsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPremium)
                    .addComponent(lblCorporateID)
                    .addComponent(lblDeductable)
                    .addComponent(lblBenefits))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateID)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBenefits))
                .addGap(27, 27, 27)
                .addComponent(btnSave)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        insuranceCoverage.setCorporateId(txtCorporateID.getText());
        insuranceCoverage.setDeductable(txtDeductable.getText());
        insuranceCoverage.setBenefits(txtBenefits.getText());
        insuranceCoverage.setPremium(txtPremium.getText());
        JOptionPane.showMessageDialog(this, "Insurance Coverage Info Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCorporateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorporateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorporateIDActionPerformed

    private void txtDeductableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeductableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeductableActionPerformed

    private void txtBenefitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenefitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenefitsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorporateID;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtPremium;
    // End of variables declaration//GEN-END:variables
}
